name: "Update image and push to Github Packages and Docker Hub weekly"

on:
  schedule:
    - cron: "0 12 * * 1" # Run every Monday at noon.
  workflow_dispatch:

jobs:
  rebuild-container:
    name: "Rebuild Container with the latest base image"
    runs-on: ubuntu-latest
    steps:
      - 
        name: Prepare outputs
        id: prep
        run: |
          echo "::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
        with:
          platforms: linux/arm64
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Login to DockerHub
        uses: docker/login-action@v3.0.0 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Checkout repository
        uses: actions/checkout@v4
      - 
        name: Get short SHA
        id: get_short_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - 
        name: Build and push to Docker Hub and GitHub Packages Docker Registry
        id: docker_build
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/public-pool:latest
            ghcr.io/${{ github.repository_owner }}/public-pool:${{ steps.get_short_sha.outputs.sha_short }}
            ${{ secrets.DOCKER_USERNAME }}/public-pool:latest
            ${{ secrets.DOCKER_USERNAME }}/public-pool:${{ steps.get_short_sha.outputs.sha_short }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
